/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1deb4ce9-78f2-42ee-ba85-4266e66390a7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zeddpWLBk",
    "aws_user_pools_web_client_id": "16i4npi7n289p4uqqmihn58uv5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://y65skph4wzhclnajwswivd2zbm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
